# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_broccoli_intern')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_broccoli_intern')
    _broccoli_intern = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_broccoli_intern', [dirname(__file__)])
        except ImportError:
            import _broccoli_intern
            return _broccoli_intern
        try:
            _mod = imp.load_module('_broccoli_intern', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _broccoli_intern = swig_import_helper()
    del swig_import_helper
else:
    import _broccoli_intern
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

BRO_TYPE_UNKNOWN = _broccoli_intern.BRO_TYPE_UNKNOWN
BRO_TYPE_BOOL = _broccoli_intern.BRO_TYPE_BOOL
BRO_TYPE_INT = _broccoli_intern.BRO_TYPE_INT
BRO_TYPE_COUNT = _broccoli_intern.BRO_TYPE_COUNT
BRO_TYPE_COUNTER = _broccoli_intern.BRO_TYPE_COUNTER
BRO_TYPE_DOUBLE = _broccoli_intern.BRO_TYPE_DOUBLE
BRO_TYPE_TIME = _broccoli_intern.BRO_TYPE_TIME
BRO_TYPE_INTERVAL = _broccoli_intern.BRO_TYPE_INTERVAL
BRO_TYPE_STRING = _broccoli_intern.BRO_TYPE_STRING
BRO_TYPE_PATTERN = _broccoli_intern.BRO_TYPE_PATTERN
BRO_TYPE_ENUM = _broccoli_intern.BRO_TYPE_ENUM
BRO_TYPE_TIMER = _broccoli_intern.BRO_TYPE_TIMER
BRO_TYPE_PORT = _broccoli_intern.BRO_TYPE_PORT
BRO_TYPE_IPADDR = _broccoli_intern.BRO_TYPE_IPADDR
BRO_TYPE_SUBNET = _broccoli_intern.BRO_TYPE_SUBNET
BRO_TYPE_ANY = _broccoli_intern.BRO_TYPE_ANY
BRO_TYPE_TABLE = _broccoli_intern.BRO_TYPE_TABLE
BRO_TYPE_UNION = _broccoli_intern.BRO_TYPE_UNION
BRO_TYPE_RECORD = _broccoli_intern.BRO_TYPE_RECORD
BRO_TYPE_LIST = _broccoli_intern.BRO_TYPE_LIST
BRO_TYPE_FUNC = _broccoli_intern.BRO_TYPE_FUNC
BRO_TYPE_FILE = _broccoli_intern.BRO_TYPE_FILE
BRO_TYPE_VECTOR = _broccoli_intern.BRO_TYPE_VECTOR
BRO_TYPE_ERROR = _broccoli_intern.BRO_TYPE_ERROR
BRO_TYPE_PACKET = _broccoli_intern.BRO_TYPE_PACKET
BRO_TYPE_SET = _broccoli_intern.BRO_TYPE_SET
BRO_TYPE_MAX = _broccoli_intern.BRO_TYPE_MAX
BRO_CFLAG_NONE = _broccoli_intern.BRO_CFLAG_NONE
BRO_CFLAG_RECONNECT = _broccoli_intern.BRO_CFLAG_RECONNECT
BRO_CFLAG_ALWAYS_QUEUE = _broccoli_intern.BRO_CFLAG_ALWAYS_QUEUE
BRO_CFLAG_SHAREABLE = _broccoli_intern.BRO_CFLAG_SHAREABLE
BRO_CFLAG_DONTCACHE = _broccoli_intern.BRO_CFLAG_DONTCACHE
BRO_CFLAG_YIELD = _broccoli_intern.BRO_CFLAG_YIELD
BRO_CFLAG_CACHE = _broccoli_intern.BRO_CFLAG_CACHE

def bro_init(ctx):
    return _broccoli_intern.bro_init(ctx)
bro_init = _broccoli_intern.bro_init

def bro_conn_new_str(hostname, flags):
    return _broccoli_intern.bro_conn_new_str(hostname, flags)
bro_conn_new_str = _broccoli_intern.bro_conn_new_str

def bro_conn_set_class(bc, classname):
    return _broccoli_intern.bro_conn_set_class(bc, classname)
bro_conn_set_class = _broccoli_intern.bro_conn_set_class

def bro_conn_connect(bc):
    return _broccoli_intern.bro_conn_connect(bc)
bro_conn_connect = _broccoli_intern.bro_conn_connect

def bro_conn_process_input(bc):
    return _broccoli_intern.bro_conn_process_input(bc)
bro_conn_process_input = _broccoli_intern.bro_conn_process_input

def bro_event_queue_length(bc):
    return _broccoli_intern.bro_event_queue_length(bc)
bro_event_queue_length = _broccoli_intern.bro_event_queue_length

def bro_event_new(event_name):
    return _broccoli_intern.bro_event_new(event_name)
bro_event_new = _broccoli_intern.bro_event_new

def bro_event_free(be):
    return _broccoli_intern.bro_event_free(be)
bro_event_free = _broccoli_intern.bro_event_free

def bro_event_add_val(be, type):
    return _broccoli_intern.bro_event_add_val(be, type)
bro_event_add_val = _broccoli_intern.bro_event_add_val

def bro_event_send(bc, be):
    return _broccoli_intern.bro_event_send(bc, be)
bro_event_send = _broccoli_intern.bro_event_send

def bro_event_registry_add_compact(bc, event_name, func):
    return _broccoli_intern.bro_event_registry_add_compact(bc, event_name, func)
bro_event_registry_add_compact = _broccoli_intern.bro_event_registry_add_compact

def bro_util_current_time():
    return _broccoli_intern.bro_util_current_time()
bro_util_current_time = _broccoli_intern.bro_util_current_time

def bro_conn_get_fd(bc):
    return _broccoli_intern.bro_conn_get_fd(bc)
bro_conn_get_fd = _broccoli_intern.bro_conn_get_fd

def bro_conn_delete(bc):
    return _broccoli_intern.bro_conn_delete(bc)
bro_conn_delete = _broccoli_intern.bro_conn_delete

def bro_conn_alive(bc):
    return _broccoli_intern.bro_conn_alive(bc)
bro_conn_alive = _broccoli_intern.bro_conn_alive
# This file is compatible with both classic and new-style classes.


