# This file was automatically generated by bifcl from const.bif.

##! Declaration of various scripting-layer constants that the Bro core uses
##! internally.  Documentation and default values for the scripting-layer
##! variables themselves are found in :doc:`/scripts/base/init-bare.bro`.

export {






















} # end of export section
module GLOBAL;
