# This file was automatically generated by bifcl from /tmp/bro-20180829-84347-dlsyak/bro-2.5.5/src/file_analysis/analyzer/unified2/types.bif (plugin mode).

export {


} # end of export section
module GLOBAL;
