# This file was automatically generated by bifcl from /tmp/bro-20180829-84347-dlsyak/bro-2.5.5/src/input/readers/binary/binary.bif (plugin mode).


export {
module InputBinary;



} # end of export section
module GLOBAL;
