# This file was automatically generated by bifcl from /tmp/bro-20180829-84347-dlsyak/bro-2.5.5/src/analyzer/protocol/ssl/functions.bif (plugin mode).


export {


## Sets if the SSL analyzer should consider the connection established (handshake
## finished succesfully).
##
## c: The SSL connection.
global set_ssl_established: function(c: connection ): any ;

} # end of export section
module GLOBAL;
