# This file was automatically generated by bifcl from /tmp/bro-20180829-84347-dlsyak/bro-2.5.5/src/analyzer/protocol/smtp/functions.bif (plugin mode).


export {


## Skips SMTP data until the next email in a connection.
##
## c: The SMTP connection.
##
## .. bro:see:: skip_http_entity_data
global skip_smtp_data: function(c: connection ): any ;

} # end of export section
module GLOBAL;
