# This file was automatically generated by bifcl from /tmp/bro-20180829-84347-dlsyak/bro-2.5.5/src/file_analysis/analyzer/extract/functions.bif (plugin mode).

##! Internal functions used by the extraction file analyzer.

export {
module FileExtract;




## :bro:see:`FileExtract::set_limit`.
global FileExtract::__set_limit: function(file_id: string , args: any , n: count ): bool ;


module GLOBAL;

} # end of export section
module GLOBAL;
