# This file was automatically generated by bifcl from /tmp/bro-20180829-84347-dlsyak/bro-2.5.5/src/analyzer/protocol/interconn/events.bif (plugin mode).



## Deprecated. Will be removed.
export {
global interconn_stats: event(c: connection , os: interconn_endp_stats , rs: interconn_endp_stats );


## Deprecated. Will be removed.
global interconn_remove_conn: event(c: connection );


} # end of export section
module GLOBAL;
