# This file was automatically generated by bifcl from /tmp/bro-20180829-84347-dlsyak/bro-2.5.5/src/input/readers/sqlite/sqlite.bif (plugin mode).


export {
module InputSQLite;





} # end of export section
module GLOBAL;
