# This file was automatically generated by bifcl from /tmp/bro-20180829-84347-dlsyak/bro-2.5.5/src/analyzer/protocol/krb/types.bif (plugin mode).

export {
module KRB;
















module GLOBAL;

} # end of export section
module GLOBAL;
