# This file was automatically generated by bifcl from /tmp/bro-20180829-84347-dlsyak/bro-2.5.5/src/logging/writers/none/none.bif (plugin mode).




export {
module LogNone;



} # end of export section
module GLOBAL;
